export {userIcon} from './userIcon';
export {uploadDataIcon} from './uploadDataIcon';
export {addOrderIcon} from './addOrderIcon';
export {forSendingIcon} from './forSendingIcon';
export {toOrderIcon} from './toOrderIcon';
export {usersIcon} from './usersIcon';
export {binIcon} from './binIcon';
export {pencilIcon} from './pencilIcon';
export {plusIcon} from './plusIcon';